version: '3'
services:
  web:
    image: python:3.10-alpine
    command: sh -c "pip install -r /app/requirements.txt && python /app/main.py"
    volumes:
      - ./src:/app
    networks:
      - proxy
    environment:
      - PYTHONUNBUFFERED=1
   
    restart: unless-stopped

networks:
  proxy:
    name: nginx-proxy-manager_default
    external: true
